# Generated by Django 5.2.6 on 2025-11-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detection", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detectionresult",
            name="face_coordinates",
            field=models.TextField(),
        ),
    ]
